#!/bin/bash
#
# SessionStart hook — provision the JDK toolchain jresolve's build requires.
#
# Why this exists: D14 pins compilation to a JDK 17 toolchain so that
# `maven.compiler.release=8` is reproducible (see docs/design-decisions.md#d14).
# The pin lives in ~/.m2/toolchains.xml, which is deliberately not part of the
# repo — so a fresh container has no toolchain and `mvn verify` fails at
# maven-toolchains-plugin with "No toolchain found for type jdk".
#
# Local machines are left alone: this runs only in Claude Code on the web.

set -euo pipefail

if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  exit 0
fi

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"

# Take the required version from the pom so this tracks the build rather than
# duplicating it. Falls back to 17 if the property is ever renamed.
JDK_VERSION="$(sed -n 's:.*<toolchain\.jdk\.version>\([0-9][0-9]*\)</toolchain\.jdk\.version>.*:\1:p' \
  "$PROJECT_DIR/pom.xml" | head -1)"
JDK_VERSION="${JDK_VERSION:-17}"

if [ "$(id -u)" -eq 0 ]; then
  SUDO=""
else
  SUDO="sudo"
fi

find_jdk_home() {
  local home
  for home in /usr/lib/jvm/java-"${JDK_VERSION}"-openjdk-* \
              /usr/lib/jvm/java-1."${JDK_VERSION}".0-openjdk-* \
              /usr/lib/jvm/*-"${JDK_VERSION}"-*; do
    if [ -x "$home/bin/javac" ]; then
      printf '%s\n' "$home"
      return 0
    fi
  done
  return 1
}

# ---------------------------------------------------------------- install JDK
if ! JDK_HOME="$(find_jdk_home)"; then
  echo "jresolve: installing JDK ${JDK_VERSION} for the build toolchain..."
  # The image ships a stale apt index, so the install 404s without this.
  # Third-party PPAs in the image fail behind the proxy; their warnings are
  # not fatal and must not take the hook down under `set -e`.
  $SUDO apt-get update -qq || echo "jresolve: apt-get update reported errors; continuing"
  $SUDO DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    "openjdk-${JDK_VERSION}-jdk-headless" >/dev/null

  if ! JDK_HOME="$(find_jdk_home)"; then
    echo "jresolve: ERROR - JDK ${JDK_VERSION} still not found under /usr/lib/jvm after install." >&2
    exit 1
  fi
fi
echo "jresolve: JDK ${JDK_VERSION} at ${JDK_HOME}"

# --------------------------------------------------------- write toolchains.xml
# Idempotent: rewritten only when it does not already point at this JDK home.
TOOLCHAINS="${HOME}/.m2/toolchains.xml"
if [ -f "$TOOLCHAINS" ] && grep -qF "<jdkHome>${JDK_HOME}</jdkHome>" "$TOOLCHAINS"; then
  echo "jresolve: ${TOOLCHAINS} already provides JDK ${JDK_VERSION}"
else
  mkdir -p "${HOME}/.m2"
  cat > "$TOOLCHAINS" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by .claude/hooks/session-start.sh. Not part of the repo; see
     docs/design-decisions.md#d14 and docs/architecture.md#building. -->
<toolchains xmlns="http://maven.apache.org/TOOLCHAINS/1.1.0"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://maven.apache.org/TOOLCHAINS/1.1.0 http://maven.apache.org/xsd/toolchains-1.1.0.xsd">
  <toolchain>
    <type>jdk</type>
    <provides>
      <version>${JDK_VERSION}</version>
      <vendor>openjdk</vendor>
    </provides>
    <configuration>
      <jdkHome>${JDK_HOME}</jdkHome>
    </configuration>
  </toolchain>
</toolchains>
EOF
  echo "jresolve: wrote ${TOOLCHAINS}"
fi

# ------------------------------------------------------------ warm the m2 cache
# The container image ships an empty ~/.m2/repository, so the first build pays
# for every plugin and dependency. Container state is cached after this hook,
# so paying it here means `mvn verify` is fast for the rest of the session.
#
# A failing suite must not fail session start — the point is the cache, not the
# verdict. The agent runs `mvn verify` itself and reads the real result there.
echo "jresolve: warming the Maven cache (first run downloads the plugin set)..."
if (cd "$PROJECT_DIR" && mvn -B -ntp -q verify >/dev/null 2>&1); then
  echo "jresolve: warm-up build passed; toolchain is working"
else
  echo "jresolve: warm-up build did not pass — dependencies are cached anyway."
  echo "jresolve: run 'mvn clean verify' to see the failure."
fi
